### ISSUE TITLE
src/Exception.c:176:12: error: equality comparison with extraneous parentheses [-Werror,-Wparentheses-equality]

### ISSUE THREAD

**Issue by abl** [orangeduck/libCello#78]
Normally I'd submit a PR, but it'd take awhile to get approval, and it's a fairly trivial fix. :)

I'm getting `src/Exception.c:176:12: error: equality comparison with extraneous parentheses [-Werror,-Wparentheses-equality]` when building libCello on OS X. (GCC details below.)

The offending line is:

```c
  if (var_list_end(vl)) {
```

which is expanded by the rule

```c
#define var_list_end(vl) (*vl is Undefined)
```

in to

```c
  if ((*vl == Undefined)) {
```

Which triggers the `-Wparentheses-equality` warning which becomes an error.

The fix I found is to simply add `-Wno-parentheses-equality` to the Makefile CFLAGS (iff using clang for maximum portability.)

---

❯ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix

**Comment by orangeduck** [comment]
Thanks for the good report! I'll make this change now.

**Comment by abl** [comment]
Thanks for the rapid change :D just discovered libCello recently and excited to play with it.
