### ISSUE TITLE
Bug in Map_Discard()

### ISSUE THREAD

**Issue by zhangchn** [orangeduck/libCello#79]
In the following code snippet:

    void testMap(){
        var m = new(Map);
        put(m, new(String,$(String, "oed")),
            new(Real,$(Real, 20.0)));
        put(m, new(String,$(String, "ci")),
            new(Real,$(Real, 4.0)));
        put(m, new(String,$(String, "cl")),
            new(Real,$(Real, 30.0)));
        put(m, new(String,$(String, "pl")),
            new(Real,$(Real, 7)));
        put(m, new(String,$(String, "od")),
            new(Real,$(Real, 7)));
        put(m, new(String,$(String, "sd")),
            new(Real,$(Real, 7)));
        put(m, new(String,$(String, "osd")),
            new(Real,$(Real, 7)));
        destroyObject(m);
    }
    void destroyObject(var object)
    {
        while (not is_empty(object)) 
        {
            var key = iter_start(object);
            var val = get(object, key);
            discard(object, key);
            delete(val);
            delete(key);
        }
    }

When the test procedure is run, the `Map_Discard()` was called to remove node for key "oed", which happened to be the root node in the node tree, and the `Map_Discard()` would first call itself to remove the right child with key "od", replacing leaf key and value of root node with the those of deleted child node, and this effectively removed the root node.

By recursively calling itself, `Map_Discard()` removed the both the keys of the root node ("oed") and the right child ("od") from `md->keys` and kept the contents of right child in the tree. This introduced an inconsistent state of key list v.s. node tree.

**Comment by zhangchn** [comment]
Maybe the `inorder_key` should be pushed back into `md->keys` after the recursive call.

**Comment by orangeduck** [comment]
Thanks for the bug report and pull request. Yes it looks like the algorithm shouldn't really call `discard` recursively because actually it is doing a swap not a discard - but I think your fix is the simpliest way to deal with it because it is better not to write a separate swapping routine. Does your commit pass the test suite if you run `make check`?

**Comment by zhangchn** [comment]
Yes. It did pass.

      +---------------------------------------------------+
      |                      Summary                      |
      +---------++------------+-------------+-------------+
      | Suites  || Total    6 | Passed    6 | Failed    0 |
      | Tests   || Total  117 | Passed  117 | Failed    0 |
      | Asserts || Total  698 | Passed  698 | Failed    0 |
      +---------++------------+-------------+-------------+
  
          Total Running Time: 0.096s

**Comment by orangeduck** [comment]
Thanks I'll merge it in.
